name: Deploy to AWS S3
description: Deploy the website to an S3 bucket
inputs:
  bucket-name:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  source-dir:
    description: 'The directory to deploy'
    required: true
  region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  using: 'docker'
  image: 'Dockerfile'