name: Testing
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - develop
  #     - homol
  #     - main
  # pull_request:
  # workflow_run:
  #   workflows: ["Build"]
  #   types:
  #     - completed
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print ref_name
        run: echo ${{ github.ref_name }}

  # foo:
  #   if: github.event_name == 'push' && github.ref_name == 'develop'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "foo"
  # bar:
  #   if: |
  #     always() && !failure() && !cancelled() &&
  #     github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   needs: foo
  #   steps:
  #     - run: echo "bar"


  # version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       run: echo '${{ toJSON(github) }}'
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.workflow_run.head_branch || github.ref }}
  #     - name: Print version file
  #       env:
  #         BRANCH: ${{ github.event.workflow_run.head_branch || github.ref }}
  #       run: |
  #         echo "Version file content:"
  #         cat version.txt
  #         echo "BRANCH: $BRANCH"
  # set-env:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     environment: ${{ steps.set-env.outputs.ENVIRONMENT }}
  #   steps:
  #     - name: Set Environment
  #       id: set-env
  #       run: |
  #         if [[ ${{ github.event_name }} == "push" ]]; then
  #           if [[ "${{ github.ref_name }}" == "develop" ]]; then
  #             echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.ref_name }}" == "homol" ]]; then
  #             echo "ENVIRONMENT=hml" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.ref_name }}" == "main" ]]; then
  #             echo "ENVIRONMENT=prd" >> $GITHUB_OUTPUT
  #           fi
  #         elif [[ ${{ github.event_name}} == "pull_request" ]]; then
  #           if [[ "${{ github.base_ref }}" == "develop" ]]; then
  #             echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.base_ref }}" == "homol" ]]; then
  #             echo "ENVIRONMENT=hml" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.base_ref }}" == "main" ]]; then
  #             echo "ENVIRONMENT=prd" >> $GITHUB_OUTPUT
  #           fi
  #         fi
  #     - name: Print Environment
  #       run: echo ${{ steps.set-env.outputs.ENVIRONMENT || 'No environment set' }}
  #     - name: Print head_branch
  #       if: ${{ github.event_name == 'workflow_run' }}
  #       run: echo ${{ github.event.workflow_run.head_branch }}
  #     - name: Print dispatch branch
  #       if: ${{ github.event_name == 'workflow_dispatch' }}
  #       run: echo ${{ github.event.workflow.dispatch.branch }}
  
  # test-env:
  #   runs-on: ubuntu-latest
  #   needs: set-env
  #   environment: ${{ needs.set-env.outputs.environment }}
  #   steps:
  #     - name: Print Environment
  #       run: echo ${{ needs.set-env.outputs.environment }}
  #     - name: Print head_branch
  #       if: ${{ github.event_name == 'workflow_run' }}
  #       run: echo ${{ github.event.workflow_run.head_branch }}
  #     - name: Print dispatch branch
  #       if: ${{ github.event_name == 'workflow_dispatch' }}
  #       run: echo ${{ github.event.workflow.dispatch.branch }}