name: Testing
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs: 
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Name
        run: echo ${{ github.event_name }}