name: Testing
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Print version file
        run: |
          echo "Version file content:"
          cat version.txt
  # set-env:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     environment: ${{ steps.set-env.outputs.ENVIRONMENT }}
  #   steps:
  #     - name: Set Environment
  #       id: set-env
  #       run: |
  #         if [[ ${{ github.event_name }} == "push" ]]; then
  #           if [[ "${{ github.ref_name }}" == "develop" ]]; then
  #             echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.ref_name }}" == "homol" ]]; then
  #             echo "ENVIRONMENT=hml" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.ref_name }}" == "main" ]]; then
  #             echo "ENVIRONMENT=prd" >> $GITHUB_OUTPUT
  #           fi
  #         elif [[ ${{ github.event_name}} == "pull_request" ]]; then
  #           if [[ "${{ github.base_ref }}" == "develop" ]]; then
  #             echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.base_ref }}" == "homol" ]]; then
  #             echo "ENVIRONMENT=hml" >> $GITHUB_OUTPUT
  #           elif [[ "${{ github.base_ref }}" == "main" ]]; then
  #             echo "ENVIRONMENT=prd" >> $GITHUB_OUTPUT
  #           fi
  #         fi
  #     - name: Print Environment
  #       run: echo ${{ steps.set-env.outputs.ENVIRONMENT || 'No environment set' }}
  #     - name: Print head_branch
  #       if: ${{ github.event_name == 'workflow_run' }}
  #       run: echo ${{ github.event.workflow_run.head_branch }}
  #     - name: Print dispatch branch
  #       if: ${{ github.event_name == 'workflow_dispatch' }}
  #       run: echo ${{ github.event.workflow.dispatch.branch }}
  
  # test-env:
  #   runs-on: ubuntu-latest
  #   needs: set-env
  #   environment: ${{ needs.set-env.outputs.environment }}
  #   steps:
  #     - name: Print Environment
  #       run: echo ${{ needs.set-env.outputs.environment }}
  #     - name: Print head_branch
  #       if: ${{ github.event_name == 'workflow_run' }}
  #       run: echo ${{ github.event.workflow_run.head_branch }}
  #     - name: Print dispatch branch
  #       if: ${{ github.event_name == 'workflow_dispatch' }}
  #       run: echo ${{ github.event.workflow.dispatch.branch }}