name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump event context
        run: echo '${{ toJSON(github.event) }}'
