name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - closed
permissions:
  contents: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump event context
        run: echo '${{ toJSON(github.event) }}'
      - name: Trigger CICD workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: version-bumped
          client-payload: '{"base_ref": "${{ github.base_ref }}"}'