name: Testing
on:
  push:
  pull_request:
jobs: 
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        id: set-env
        run: |
          if [[ ${{ github.ref_name }} == "develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref_name }} == "homol" ]]; then
            echo "ENVIRONMENT=hml" >> $GITHUB_ENV
          elif [[ ${{ github.ref_name }} == "main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          fi
      - name: Print Environment
        run: echo ${{ env.ENVIRONMENT }}