name: Testing
on:
  push:
  pull_request:
jobs: 
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Print information
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "head_ref: ${{ github.head_ref	}}"
          echo "base_ref: ${{ github.base_ref}}""