name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact:
        description: 'The artifact to deploy'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
      - name: List files
        run: ls -l
      - name: Output information
        run: echo "Deploying to ${{ github.ref }}"